ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '01695402297';
flush privileges;

CREATE DATABASE SHOPBAN_QUANAO;

USE SHOPBAN_QUANAO;

CREATE TABLE THUONGHIEU (
	MA_THUONGHIEU INT AUTO_INCREMENT NOT NULL,
	TEN_THUONGHIEU VARCHAR(50) NOT NULL,
	PRIMARY KEY (MA_THUONGHIEU)
);

INSERT INTO THUONGHIEU (TEN_THUONGHIEU)
VALUES ('No brand'),
	   ('Abercrombie & Fitch'),
       ('Adidas'),
       ('Aeropostale'),
       ('Aj Morgan'),
       ('Aldo'),
       ('ĐAN CHÂU');
       
CREATE TABLE CHATLIEU (
	MA_CHATLIEU INT AUTO_INCREMENT NOT NULL,
    TEN_CHATLIEU VARCHAR(50) NOT NULL,
    PRIMARY KEY (MA_CHATLIEU)
);

INSERT INTO CHATLIEU (TEN_CHATLIEU)
VALUES ('Dây'),
	   ('Lông cừu'),
       ('Len đan'),
       ('Len acrylic'),
       ('Cashmere'),
       ('Cotton');
       
CREATE TABLE LOAI_SP0 (
	MA_LOAI0 INT AUTO_INCREMENT NOT NULL,
    TEN_LOAI0 VARCHAR(50) NOT NULL,
    PRIMARY KEY (MA_LOAI0)
);

INSERT INTO LOAI_SP0 (TEN_LOAI0)
VALUES ('Quần áo nam'),
	   ('Quần áo nữ');
       
CREATE TABLE LOAI_SP1 (
	MA_LOAI1 INT AUTO_INCREMENT NOT NULL,
    TEN_LOAI1 VARCHAR(50) NOT NULL,
    MA_LOAI0 INT NOT NULL,
    PRIMARY KEY (MA_LOAI1),
    FOREIGN KEY (MA_LOAI0) REFERENCES LOAI_SP0(MA_LOAI0)
);

INSERT INTO LOAI_SP1 (TEN_LOAI1, MA_LOAI0)
VALUES ('Áo thun', 1),
	   ('Áo sơ mi', 1),
       ('Áo', 2),
	   ('Chân váy', 2);

CREATE TABLE LOAI_SP2 (
	MA_LOAI2 INT AUTO_INCREMENT NOT NULL,
    TEN_LOAI2 VARCHAR(50) NOT NULL,
	MA_LOAI1 INT NOT NULL,
    PRIMARY KEY (MA_LOAI2),
    FOREIGN KEY (MA_LOAI1) REFERENCES LOAI_SP1(MA_LOAI1)
);

INSERT INTO LOAI_SP2 (TEN_LOAI2, MA_LOAI1)
VALUES ('Áo len', 1),
	   ('Áo ngắn tay có cổ', 1),
       ('Dài tay', 2),
	   ('Ngắn tay', 2),
       ('Áo Croptop', 3),
	   ('Áo sơ mi', 3),
       ('Chân váy xoè', 4),
	   ('Chân váy ngắn', 4);
       
CREATE TABLE SANPHAM (
	MA_SANPHAM INT NOT NULL,
    TEN_SANPHAM VARCHAR(250) NOT NULL,
    MA_LOAI2 INT NOT NULL,
    MA_THUONGHIEU INT NOT NULL,
    MA_CHATLIEU INT NOT NULL,
    -- KHOILUONG INT DEFAULT 0,
    MOTA TEXT NULL,
    GIABAN INT NOT NULL DEFAULT 0,
    KHUYENMAI TINYINT DEFAULT 0,
	HINHANH VARCHAR(1000) NOT NULL,
    SOLUONGTON INT DEFAULT 0,
    PRIMARY KEY (MA_SANPHAM),
    FOREIGN KEY (MA_LOAI2) REFERENCES LOAI_SP2 (MA_LOAI2),
    FOREIGN KEY (MA_THUONGHIEU) REFERENCES THUONGHIEU (MA_THUONGHIEU),
    FOREIGN KEY (MA_CHATLIEU) REFERENCES CHATLIEU (MA_CHATLIEU)
);


INSERT INTO SANPHAM (MA_SANPHAM, TEN_SANPHAM, MA_LOAI2, MA_THUONGHIEU, MA_CHATLIEU, MOTA, GIABAN, KHUYENMAI, HINHANH, SOLUONGTON)
VALUES (1, 'SƠ MI TRẮNG TAY DÀI', 3, 1, 6, '🌈🌈🌈SƠ MI NAM WHITE & BLACK
⛔️ ÁO BÊN Ý ĐẶT MAY NHÉ!!! chất lượng đẹp từng cái - BAO ĐỔI NẾU HÀNG KÉM CHẤT LƯỢNG.
⚡️⚡️⚡️ Giá lẻ: 170k
⚡️⚡️⚡️ Giá sỉ 5sp: 145k 
❣️ Shopee: shopee.vn/menshopgiare
❣️ Size: M - L XL - XXL
📞📞 CALL/ ZALO: 0987.96.4243', 200000, 46, 'HINHANH', 200);

CREATE TABLE KHACHHANG (
	MA_KHACHHANG INT NOT NULL,
    TAIKHOAN VARCHAR(50) NOT NULL,
    MATKHAU VARCHAR(50) NOT NULL,
    TEN_KHACHHANG VARCHAR(100) NULL,
    DIENTHOAI VARCHAR(20) NULL,
    `TINH/THANHPHO` VARCHAR(100) NULL,
    `QUAN/HUYEN` VARCHAR(100) NULL,
    `PHUONG/XA` VARCHAR(100) NULL,
    `SONHA/DUONG` VARCHAR(100) NULL,
    AVATAR VARCHAR(100) NULL,
    PRIMARY KEY (MA_KHACHHANG)
);

INSERT INTO KHACHHANG (MA_KHACHHANG, TAIKHOAN, MATKHAU, TEN_KHACHHANG, DIENTHOAI, `TINH/THANHPHO`, `QUAN/HUYEN`, `PHUONG/XA`, `SONHA/DUONG`, AVATAR)
VALUES (1, 'caubinhphu', '1234', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

CREATE TABLE TRANGTHAI_DONHANG (
	MA_TRANGTHAI INT AUTO_INCREMENT NOT NULL,
    TEN_TRANGTHAI VARCHAR(50) NOT NULL,
    PRIMARY KEY (MA_TRANGTHAI)
);

INSERT INTO TRANGTHAI_DONHANG(TEN_TRANGTHAI)
VALUES ('Chờ xác nhận'),
	   ('Chờ lấy hàng'),
       ('Đang giao'),
       ('Đã giao'),
       ('Đã huỷ'),
       ('Trả hàng/Hoàn tiền');

CREATE TABLE GIOHANG (
	MA_KHACHHANG INT NOT NULL,
    MA_SANPHAM INT NOT NULL,
	SOLUONG INT DEFAULT 1,
    PRIMARY KEY (MA_KHACHHANG, MA_SANPHAM),
    FOREIGN KEY (MA_KHACHHANG) REFERENCES KHACHHANG (MA_KHACHHANG),
    FOREIGN KEY (MA_SANPHAM) REFERENCES SANPHAM (MA_SANPHAM)
);

INSERT INTO GIOHANG (MA_KHACHHANG, MA_SANPHAM)
VALUES (1, 1);

CREATE TABLE DONDATHANG (
	MA_DONDATHANG INT NOT NULL,
    MA_KHACHHANG INT NOT NULL,
    NGAY_DATHANG DATE,
    MA_TRANGTHAI INT NOT NULL,
    TEN_NGUOINHAN VARCHAR(100) NOT NULL,
    DIENTHOAI_NGUOINHAN VARCHAR(20) NOT NULL,
	`TINH/THANHPHO` VARCHAR(100) NOT NULL,
    `QUAN/HUYEN` VARCHAR(100) NOT NULL,
    `PHUONG/XA` VARCHAR(100) NOT NULL,
    `SONHA/DUONG` VARCHAR(100) NOT NULL,
    PHI_VANCHUYEN INT DEFAULT 0,
    NGAY_XUATHANG DATE,
    NGAY_GIAOHANG DATE,
    PRIMARY KEY (MA_DONDATHANG),
    FOREIGN KEY (MA_KHACHHANG) REFERENCES KHACHHANG (MA_KHACHHANG),
    FOREIGN KEY (MA_TRANGTHAI) REFERENCES TRANGTHAI_DONHANG (MA_TRANGTHAI)
);

CREATE TABLE CT_DONDATHANG (
	MA_DONDATHANG INT NOT NULL,
    MA_SANPHAM INT NOT NULL,
    SOLUONG INT DEFAULT 1,
    GIAGOC INT DEFAULT 0,
    KHUYENMAI INT DEFAULT 0,
    PRIMARY KEY (MA_DONDATHANG, MA_SANPHAM),
    FOREIGN KEY (MA_DONDATHANG) REFERENCES DONDATHANG (MA_DONDATHANG),
    FOREIGN KEY (MA_SANPHAM) REFERENCES SANPHAM (MA_SANPHAM)
);

select * from khachhang;

DELIMITER $$
create procedure sp_test()
begin
	select * from khachhang;
    select * from thuonghieu;
end $$
DELIMITER ;

call sp_test();

select * from khachhang;

create table test (
	id int auto_increment primary key,
    col1 varchar(10) not null, 
    col2 int not null
);
insert into test (col1, col2) values ('một', 1), ('hai', 2);

select * from test;
